---
version: "3.8"

services:
  database:
    container_name: database
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    hostname: database
    image: postgis/postgis:17-3.4 # if using crunchy , make sure to align with crunchy version, currently it is at 16 and postgis 3.3
    restart: always
    volumes:
      - /pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "default"]
    ports: ["5432:5432"]

  backend:
    container_name: backend
    entrypoint:
      - "sh"
      - "-c"
      - "npm i && npm run start"
    environment:
      NODE_ENV: development
      POSTGRESQL_HOST: database
      POSTGRESQL_USER: default
      POSTGRESQL_PASSWORD: default
      POSTGRESQL_DATABASE: default
      object_store_bucket: epdsbx
      object_store_host: nrs.objectstore.gov.bc.ca
      object_store_secret: ${object_store_secret}
      object_store_userid: ${object_store_userid}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: backend
    image: node:22
    links:
      - database
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app:z
      - /app/node_modules
    working_dir: "/app"

  frontend:
    container_name: frontend
    entrypoint:
      - "sh"
      - "-c"
      - "npm i && npm run start"
    environment:
      NODE_ENV: development
      BACKEND_URL: http://backend
      COOKIE_SECRET: ${COOKIE_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: frontend
    depends_on:
        backend:
          condition: service_healthy
    image: esra-frontend/image:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    links:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    working_dir: "/app"

  schemaspy:
    image: schemaspy/schemaspy:7.0.2
    profiles: ["schemaspy"]
    container_name: schemaspy
    command: -t pgsql11 -db postgres -host database -port 5432 -u postgres -p default -schemas users
    depends_on:
      migrations:
        condition: service_completed_successfully
    volumes: ["./output:/output"]

  caddy:
    container_name: caddy
    profiles: ["caddy"]
    build: ./frontend
    environment:
      NODE_ENV: development
      PORT: 3000
      BACKEND_URL: http://backend:3000
      LOG_LEVEL: info
    ports: ["3005:3000"]
    volumes: ["./frontend/Caddyfile:/etc/caddy/Caddyfile"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    depends_on:
      backend:
        condition: service_healthy
