name: Scheduled

on:
  schedule: [cron: "0 9 * * *"] # every midnight
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rollout_frontend:
    name: Rollout frontend
    environment: prod
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Rollout frontend to remove defunt pids # temporary solution
        uses: bcgov/action-oc-runner@v0.3.0
        with:
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_token: ${{ secrets.oc_token }}
          oc_server: ${{ vars.oc_server }}
          commands: |
            oc rollout latest dc/esra-prod-frontend
            oc rollout status dc/esra-prod-frontend
            
